CREATE FUNCTION `user_get_code_f`(uID INT) RETURNS VARCHAR(3)
	READS SQL DATA
BEGIN
	DECLARE Res VARCHAR(3) DEFAULT NULL;
	IF(user_test_f(uID,TRUE)!=1) THEN
		RETURN NULL;
	END IF;
    SELECT usr_Code INTO Res FROM BGM_Users WHERE usr_ID=uID;
    RETURN Res;
END;
